services:
  front:
    build: .
    ports:
      - 127.0.0.1:8000:12000
    working_dir: /app
    image: dangnguyen1012/image-store:latest
    volumes:
      - type: bind
        source: /Users/phucdang/Documents/Workspace/java/imageStore
        target: /app
  end:
    build: .
    ports:
      - 127.0.0.1:8000:12000
    working_dir: /app
    image: dangnguyen1012/image-store:latest
    volumes:
      - type: bind
        source: /Users/phucdang/Documents/Workspace/java/imageStore
        target: /app