# React things
FROM node:18-alpine AS development
WORKDIR /app
COPY . /app
RUN npm i
FROM development AS build
RUN npm run build

# APACHE2:
FROM nginx:alpine
COPY .nginx/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
# Copy static assets from builder stage
COPY --from=build /app/dist .
CMD ["nginx", "-g", "daemon off;"]